refactor(start): modularize 'start' into sub-procedure
$cfname is scope-inherited in sub-procedure so no need to pass it as
an argument.

diff --git a/mast b/mast
--- a/mast
+++ b/mast
@@ -101,7 +101,7 @@ _log-file() {
 }
 
 # Log piped message to stdout and in given config log file.
-# @param {string} config name
+# @param:	{string} 	$1	configuration filename.
 _log-to() {
 	if [[ -z "$1" ]]; then
 		# do NOT refactor or get a fork bomb :D!
@@ -126,37 +126,46 @@ _log-to() {
 	chmod u=rwx,g=rwx "$(_log-file  "$cfname")"
 }
 
-
-start() {
+# Make sure we have a config file
+# @param:	{string}	$config		configuration filepath.
+# @inherit:		{string} 	$cfname	configuration filename.
+check_config_file_exists() {
 	config="$1"
-	cfname="$(basename "$config")"
-	forward_list=""
 
-	# make sure we have a config file
 	if [[ ! -f "$config" ]]; then
 		feedback "$cfname"  "missing"  "no configuration file in $CONFIG_DIR"
 		return $abort_status
 	fi
+}
 
-	source "$config"
 
-	# make sure all arguments/variables have been defined in config
-	sshArguments=(
+# Make sure all arguments/variables have been defined in config
+# @inherit:		{string} 	$cfname		configuration filename.
+check_tunnel_config() {
+	sshArguments=( # list of required variables
 		ServerAliveInterval ServerAliveCountMax StrictHostKeyChecking
 		LocalUser IdentityFile RemoteUser RemoteHost RemotePort
 		BandwidthLimitation UploadLimit DownloadLimit
 	)
+
 	for var in "${sshArguments[@]}"; do
-	eval "
-		if [[ -z \$$var ]]
-		then
+		if [[ -z ${!var} ]]; then # test if each config's variable is empty (e.g. $ServerAliveInterval content)
 			feedback "$var"  "undefined"  "no value in $CONFIG_DIR/$cfname"
 			return $abort_status
 		fi
-		"
 	done
+}
 
-	if (( ${#ForwardPort[*]} == 0 )); then
+
+# We need at least 1 forward rule to be able to start
+# @inherit:		{string} 	$cfname		configuration filename.
+# @inherit:		{array}	$ForwardPort	list of SSH forwarding rules.
+check_ssh_forward_rules() {
+	# workaround the lack of ${#ForwardPort[@]} support, no logical explaination
+	for f in "${ForwardPort[@]}"; do (( rule_count++)); done
+
+	# if (( ${#ForwardPort[@]} == 0 )); then
+	if (( rule_count == 0 )); then
 		feedback "ForwardPort array"  "empty"  "no value in $CONFIG_DIR/$cfname."
 		return $abort_status
 	fi
@@ -172,42 +181,69 @@ start() {
 			;;
 		esac
 	done
+}
 
-	# define the pidfile variable for autossh (created by autossh)
-	# check if pidfile already exists -- don't start another instance if pidfile exists
-	AUTOSSH_PIDFILE="/var/run/$NAME/$cfname.pid"
+# 	check if pidfile already exists -- don't start another instance if pidfile exists
+# @inherit:	{string} 	$cfname	configuration filename.
+check_no_pid_exists() {
+	# Define the pidfile variable for autossh (created by autossh)
+	export AUTOSSH_PIDFILE="/var/run/$NAME/$cfname.pid"
 	if [[ -e $AUTOSSH_PIDFILE ]]; then
 		feedback "host PID"  "forbidden"  "PID already exists, stop service or remove $(_value "$AUTOSSH_PIDFILE")."
 		return $abort_status
 	fi
+}
 
-	printf "Starting %s %s: " "$NAME" "$cfname"
 
-	# before switching-users, make sure pidfile is created and user has write permission
+# Before switching-users, make sure pidfile is created and user has write permission
+# @inherit:	{string} 	$cfname	configuration filename.
+create_pid() {
 	touch "$AUTOSSH_PIDFILE"
 	chown "$LocalUser" "$AUTOSSH_PIDFILE"
 
+	# check to make sure pidfile was created
+	if [[ ! -f $AUTOSSH_PIDFILE ]]; then
+		feedback "$cfname's PID creation"  "aborted"  ""
+		return $abort_status
+	fi
+}
+
+
+# Start the service
+# @param:	{string}	$config		configuration filepath.
+start() {
+	config="$1"
+	cfname="$(basename "$config")"
+	forward_list=""
+
+	# abort start if one of the following fail
+	check_config_file_exists "$config"	&& source "$config"	|| return $abort_status
+	check_tunnel_config 							|| return $abort_status
+	export ForwardPortq
+	check_ssh_forward_rules		|| return $abort_status
+	check_no_pid_exists							|| return $abort_status
+	create_pid 												|| return $abort_status
+
+	printf "Starting %s %s\n" "$(_info "$NAME")" "$(_value "$cfname")"
+
+	export AUTOSSH_PIDFILE=$AUTOSSH_PIDFILE;
+	export AUTOSSH_PORT=0;
+	export AUTOSSH_LOGFILE="$LOG_DIR/$NAME-$cfname.log";
 	# start autossh as the user defined in the config file
 	# the pidfile must be re-defined in the new environment
 	su - "$LocalUser" bash -c "
-		AUTOSSH_PIDFILE=$AUTOSSH_PIDFILE;
-		AUTOSSH_PORT=0;
-		export AUTOSSH_PIDFILE AUTOSSH_PORT;
 		$autossh -q -N -p $RemotePort \
-		-i $IdentityFile \
-		-o ServerAliveInterval=$ServerAliveInterval \
-		-o ServerAliveCountMax=$ServerAliveCountMax \
-		-o StrictHostKeyChecking=$StrictHostKeyChecking \
-		$forward_list $RemoteUser@$RemoteHost -f;"
+			-i $IdentityFile \
+			-v \
+			-o ServerAliveInterval=$ServerAliveInterval \
+			-o ServerAliveCountMax=$ServerAliveCountMax \
+			-o StrictHostKeyChecking=$StrictHostKeyChecking \
+			$forward_list $RemoteUser@$RemoteHost -f \
+		&& echo 'run' \
+		|| (echo 'fail'; rm -f"$AUTOSSH_LOGFILE") \
+		"
 
-	# check to make sure pidfile was created
-	if [[ ! -f $AUTOSSH_PIDFILE ]]; then
-		printf "%s not created\n" "$(basename "$AUTOSSH_PIDFILE")" 1>&2 | _log-to "$cfname"
-		return 1
-	fi
-
-	echo
-	touch /var/lock/"$NAME"/"$cfname"
+	touch /var/lock/"$NAME/$cfname"
 }
 
 
