feat(service): add logging functions '_log-to' and '_log-file'
_log-to(): Log piped message to stdout and in given config log file.
_log-file(): Log file path for given config

diff --git a/mast b/mast
--- a/mast
+++ b/mast
@@ -38,7 +38,7 @@ RETVAL=0 # default return value
 NAME=mast
 autossh="$(which autossh)"
 # template name for log file
-LOG=/var/log/mast-_cfg_.log
+LOG_DIR="/var/log/$NAME"
 
 # Create PID directory missing
 [[ ! -d /var/run/$NAME ]] && mkdir -p /var/run/$NAME
@@ -67,6 +67,38 @@ _value()		{ printf "${_value_}%s${_reset_}" "$*"; } 				# style text as value
 _valid()			{ printf "${_valid_}%s${_reset_}" "$*"; } 				# style text as valid
 
 
+# Log file path for given config
+# @param {string} config name
+_log-file() {
+	if [[ -z "$1" ]]; then
+		printf "You must give a %s!\n" "$(_warning "config name")"
+		exit 1
+	else
+		echo "$LOG_DIR/$NAME-$1.log"
+	fi
+}
+
+# Log piped message to stdout and in given config log file.
+# @param {string} config name
+_log-to() {
+	if [[ -z "$1" ]]; then
+		printf "You must give a %s!\n" "$(_warning "config name")"
+		exit 1
+	fi
+	cfname="$1"
+	shift; read msg
+
+	# print to stdout
+	printf "%s\n" "$msg"
+
+	# print to log file
+	printf "[%s] %s\n" "$(_info "${FUNCNAME[1]}")" "$msg" >> "$(_log-file  "$cfname")"
+}
+
+
+
+
+
 start() {
 	config="$1"
 	cfname="$(basename "$config")"
@@ -74,7 +106,7 @@ start() {
 
 	# make sure we have a config file
 	if [[ ! -f "$config" ]]; then
-		printf "%s %s: %s missing\n" "$NAME" "$cfname" "$config" | tee -a "$(logConfig "$cfname")"
+		printf "%s %s: %s missing\n" "$NAME" "$cfname" "$config" | _log-to "$cfname"
 		return 1
 	fi
 
@@ -90,14 +122,14 @@ start() {
 	eval "
 		if [[ -z \$$var ]]
 		then
-			printf \"%s %s: %s variable empty\\n\" \"$NAME\" \"$cfname\" \"$var\" | tee -a \"$(logConfig \"$cfname\")\"
+			printf \"%s %s: %s variable empty\\n\" \"$NAME\" \"$cfname\" \"$var\" | _log-to \"$cfname\"
 			return 1
 		fi
 		"
 	done
 
 	if (( ${#ForwardPort[*]} == 0 )); then
-		printf "%s %s: ForwardPort array empty\n" "$NAME" "$cfname" | tee -a "$(logConfig "$cfname")"
+		printf "%s %s: ForwardPort array empty\n" "$NAME" "$cfname" | _log-to "$cfname"
 		return 1
 	fi
 
@@ -107,7 +139,7 @@ start() {
 				forward_list+="-$fwd "
 			;;
 			*)
-				printf "%s %s: %s format unknown\n" "$NAME" "$cfname" "$fwd" | tee -a "$(logConfig "$cfname")"
+				printf "%s %s: %s format unknown\n" "$NAME" "$cfname" "$fwd" | _log-to "$cfname"
 				return 1
 			;;
 		esac
@@ -117,7 +149,7 @@ start() {
 	# check if pidfile already exists -- don't start another instance if pidfile exists
 	AUTOSSH_PIDFILE="/var/run/$NAME/$cfname.pid"
 	if [[ -e $AUTOSSH_PIDFILE ]]; then
-		printf "%s %s: %s already exists\n" "$NAME" "$cfname" "$AUTOSSH_PIDFILE" | tee -a "$(logConfig "$cfname")"
+		printf "%s %s: %s already exists\n" "$NAME" "$cfname" "$AUTOSSH_PIDFILE" | _log-to "$cfname"
 		return 1
 	fi
 
@@ -142,7 +174,7 @@ start() {
 
 	# check to make sure pidfile was created
 	if [[ ! -f $AUTOSSH_PIDFILE ]]; then
-		printf "%s not created\n" "$(basename "$AUTOSSH_PIDFILE")" | tee -a "$(logConfig "$cfname")"
+		printf "%s not created\n" "$(basename "$AUTOSSH_PIDFILE")" | _log-to "$cfname"
 		return 1
 	fi
 
@@ -171,7 +203,7 @@ stop() {
 		pidfile="/var/run/$NAME/$cfname.pid"
 		if [[ ! -f "$pidfile" ]]
 		then
-			printf "%s %s: %s missing\n" "$NAME" "$cfname" "$pidfile" | tee -a "$(logConfig "$cfname")"
+			printf "%s %s: %s missing\n" "$NAME" "$cfname" "$pidfile" | _log-to "$cfname"
 			return 1
 		else
 			printf "Stopping %s %s: " "$NAME" "$cfname"
@@ -184,14 +216,6 @@ stop() {
 	return $RETVAL
 }
 
-logConfig() {
-	if [[ -z "$1" ]]; then
-		printf "Missing log file: %s\n"
-		exit 1
-	else
-		echo "${LOG/_cfg_/$1}"
-	fi
-}
 
 list() {
 	for h in *; do
