refactor(service,permission): wrap test on superuser in function
fixes #52

diff --git a/mast b/mast
--- a/mast
+++ b/mast
@@ -436,10 +436,14 @@ function iter_action_on_config() {
 }
 
 
-if (( $(id -u) != 0 )); then
-	printf "%s %s\n" "$(_error "Require")" "$(_info "sudo privileges")"
-	exit 1
-fi
+function require_superuser() {
+	if (( $(id -u) != 0 )); then
+		printf "%s %s\n" "$(_error "Require")" "$(_info "sudo privileges")"
+		exit 1
+	fi
+}
+
+require_superuser
 
 # save the action name, and shift the command-line array
 # all remaining command-line arguments *should* be config names
